name: docs

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
        with:
          version: '1.8.3'
      - run: poetry install
      - name: build docs
        run: |
          poetry run pdoc src/tastytrade_sdk --docformat numpy --no-show-source -t docs/users -o docs/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy_docs:
    needs: build_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4