name: Release to TestPyPI
concurrency:
  group: tastytrade-sdk-python-release-test
  cancel-in-progress: true
on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tastytrade-sdk
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
        with:
          version: '1.8.3'
      - run: poetry install
      - run: make lint
      - run: make test
        env:
          API_BASE_URL: ${{ vars.TASTYTRADE_CERT_URL }}
          TASTYTRADE_LOGIN: ${{ secrets.TASTYTRADE_CERT_LOGIN }}
          TASTYTRADE_PASSWORD: ${{ secrets.TASTYTRADE_CERT_PASSWORD }}
      - name: Build with Poetry
        run: |
          poetry version "$(poetry version -s)dev${GITHUB_RUN_NUMBER}"
          poetry build
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
